{
 "title": "WRF cluster - Cost",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Master Node hourly Cost",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "master_node_cost", "legendFormat": " " }
   ]
  },
  {
   "title": "EBS (Master node) hourly Cost",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ebs_master_cost", "legendFormat": " " }
   ]
  },
  {
   "title": "Cluster Total Hourly Cost",
   "type": "graph",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "currencyUSD", "label": "$ / hour" }
   ],
   "targets": [
    {
     "expr": "s3_cost+master_node_cost+fsx_cost+ebs_master_cost+compute_nodes_cost+ebs_compute_cost",
     "legendFormat": "Entire Cluster cost"
    },
    { "expr": "s3_cost", "legendFormat": "S3" },
    { "expr": "master_node_cost", "legendFormat": "Master Node" },
    { "expr": "fsx_cost", "legendFormat": "FSx" },
    { "expr": "ebs_master_cost", "legendFormat": "EBS (Master)" },
    { "expr": "compute_nodes_cost", "legendFormat": "Compute Nodes" },
    { "expr": "ebs_compute_cost", "legendFormat": "EBS (Compute)" }
   ]
  },
  {
   "title": "Compute Node hourly Cost",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "compute_nodes_cost", "legendFormat": " " }
   ]
  },
  {
   "title": "EBS (Compute nodes) hourly Cost",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ebs_compute_cost", "legendFormat": " " }
   ]
  },
  {
   "title": "FSx hourly Cost",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "fsx_cost", "legendFormat": " " }
   ]
  },
  {
   "title": "S3 hourly Cost",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "s3_cost", "legendFormat": " " }
   ]
  },
  {
   "title": "EFS hourly cost",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "s3_cost", "legendFormat": " " }
   ]
  }
 ]
}