{
 "title": "Numerical Weather Prediction on AWS with WRF - Cluster information",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Cluster Storage",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance_id=\"__INSTANCE_ID__\",fstype=~\"ext4|xfs|lustre|nfs|nfs4\"}-0"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance_id=\"__INSTANCE_ID__\",fstype=~\"ext4|xfs|lustre|nfs|nfs4\"}-0"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance_id=\"__INSTANCE_ID__\",fstype=~\"ext4|xfs|lustre|nfs|nfs4\"} / node_filesystem_size_bytes{instance_id=\"__INSTANCE_ID__\",fstype=~\"ext4|xfs|lustre|nfs|nfs4\"})"
    }
   ]
  },
  {
   "title": "FSx Total throughput ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "Bps", "label": "Total throughput (bytes/sec)" }
   ],
   "targets": [
    {
     "id": "fsxRead",
     "metricName": "DataReadBytes",
     "namespace": "AWS/FSx",
     "region": "__AWS_REGION__",
     "statistics": [ "Sum" ]
    },
    {
     "id": "fsxWrite",
     "metricName": "DataWriteBytes",
     "namespace": "AWS/FSx",
     "region": "__AWS_REGION__",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "FSx Total IOPs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "iops", "label": "Total IOPs (Operations/sec)" }
   ],
   "targets": [
    {
     "id": "fsxIOPsRead",
     "metricName": "DataReadOperations",
     "namespace": "AWS/FSx",
     "region": "__AWS_REGION__",
     "statistics": [ "Sum" ]
    },
    {
     "id": "fsxIOPsWrite",
     "metricName": "DataWriteOperations",
     "namespace": "AWS/FSx",
     "region": "__AWS_REGION__",
     "statistics": [ "Sum" ]
    }
   ]
  },
  { "title": "Scheduler Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Slurm Pending Jobs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "slurm_queue_configuring", "legendFormat": " " }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slurm_queue_completing", "legendFormat": "Completing Jobs" },
    { "expr": "slurm_queue_running", "legendFormat": "Running Jobs" },
    { "expr": "slurm_queue_pending", "legendFormat": "Pending Jobs" },
    { "expr": "slurm_queue_completed", "legendFormat": "Completed Jobs" },
    { "expr": "slurm_queue_timeout", "legendFormat": "Timed out Jobs" },
    { "expr": "slurm_queue_failed", "legendFormat": "Failed Jobs" },
    { "expr": "slurm_queue_node_fail", "legendFormat": "Failed jobs (due to NodeFail)" },
    { "expr": "slurm_queue_suspended", "legendFormat": "Suspended Jobs" },
    { "expr": "slurm_queue_cancelled", "legendFormat": "Cancelled Jobs" },
    { "expr": "slurm_queue_preempted", "legendFormat": "Preempted Jobs" }
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slurm_nodes_alloc", "legendFormat": "Allocated Nodes" },
    { "expr": "slurm_nodes_comp", "legendFormat": "Completing Nodes" },
    { "expr": "slurm_nodes_idle", "legendFormat": "Idle Nodes" },
    { "expr": "slurm_nodes_down", "legendFormat": "Down Nodes" },
    { "expr": "slurm_nodes_drain", "legendFormat": "Draining Nodes" },
    { "expr": "slurm_nodes_err", "legendFormat": "Nodes in *error* state" },
    { "expr": "slurm_nodes_fail", "legendFormat": "Nodes in *fail* state" },
    {
     "expr": "slurm_nodes_alloc + slurm_nodes_down + slurm_nodes_drain + slurm_nodes_idle + slurm_nodes_mix + slurm_nodes_comp + slurm_nodes_maint",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "Slurm Jobs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "slurm_queue_running", "legendFormat": "Running" }
   ]
  },
  { "title": "CPU, Memory & Disk Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total CPU cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\",instance_id!=\"__INSTANCE_ID__\"})"
    }
   ]
  },
  {
   "title": "Avg. CPU cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\",instance_id!=\"__INSTANCE_ID__\"})/count(count(node_cpu_seconds_total{instance_id!=\"__INSTANCE_ID__\"}) by (instance_id))"
    }
   ]
  },
  {
   "title": "Total CPU use",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",instance_id!=\"__INSTANCE_ID__\"}[1m]))"
    }
   ]
  },
  {
   "title": "Avg. CPU use",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",instance_id!=\"__INSTANCE_ID__\"}[1m]))/count(count(node_cpu_seconds_total{instance_id!=\"__INSTANCE_ID__\"}) by (instance_id))"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance_id!=\"__INSTANCE_ID__\"})"
    }
   ]
  },
  {
   "title": "Avg. Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance_id!=\"__INSTANCE_ID__\"})/count(node_memory_MemTotal_bytes{instance_id!=\"__INSTANCE_ID__\"})"
    }
   ]
  },
  {
   "title": "Total Memory use",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance_id!=\"__INSTANCE_ID__\"}) - sum(node_memory_MemAvailable_bytes{instance_id!=\"__INSTANCE_ID__\"})"
    }
   ]
  },
  {
   "title": "Avg. Memory use",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{instance_id!=\"__INSTANCE_ID__\"}) - sum(node_memory_MemAvailable_bytes{instance_id!=\"__INSTANCE_ID__\"}))/count(node_memory_MemTotal_bytes{instance_id!=\"__INSTANCE_ID__\"})"
    }
   ]
  },
  {
   "title": "Total Disk (write)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance_id!=\"__INSTANCE_ID__\"}[1m]))"
    }
   ]
  },
  {
   "title": "Avg. Disk (write)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance_id!=\"__INSTANCE_ID__\"}[1m])) / count(node_disk_written_bytes_total{instance_id!=\"__INSTANCE_ID__\"})"
    }
   ]
  },
  {
   "title": "Total Disk (read)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance_id!=\"__INSTANCE_ID__\"}[1m]))"
    }
   ]
  },
  {
   "title": "Avg. Disk (read)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance_id!=\"__INSTANCE_ID__\"}[1m])) / count(node_disk_read_bytes_total{instance_id!=\"__INSTANCE_ID__\"})"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\",instance_id!=\"__INSTANCE_ID__\"})",
     "legendFormat": "Total cores"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",instance_id!=\"__INSTANCE_ID__\"}[1m]))",
     "legendFormat": "Load in cores"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance_id!=\"__INSTANCE_ID__\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance_id!=\"__INSTANCE_ID__\"}) - sum(node_memory_MemAvailable_bytes{instance_id!=\"__INSTANCE_ID__\"})",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "Disk I/O (read)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance_id!=\"__INSTANCE_ID__\"}[1m]))",
     "legendFormat": "Read throughput"
    }
   ]
  },
  {
   "title": "Disk I/O (write)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance_id!=\"__INSTANCE_ID__\"}[1m]))",
     "legendFormat": "Write throughput"
    }
   ]
  },
  { "title": "Network Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Current Total Throughput (Transmit)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*',instance_id!=\"__INSTANCE_ID__\"}[1m]))"
    }
   ]
  },
  {
   "title": "Current Avg. Throughput per Node (Transmit)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*',instance_id!=\"__INSTANCE_ID__\"}[1m]))/count(count(node_network_transmit_bytes_total{instance_id!=\"__INSTANCE_ID__\"}) by(instance_id))"
    }
   ]
  },
  {
   "title": "Current Total Throughput (Receive)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*',instance_id!=\"__INSTANCE_ID__\"}[1m]))"
    }
   ]
  },
  {
   "title": "Current Avg. Throughput per Node (Receive)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*',instance_id!=\"__INSTANCE_ID__\"}[1m]))/count(count(node_network_receive_bytes_total{instance_id!=\"__INSTANCE_ID__\"}) by(instance_id))"
    }
   ]
  },
  {
   "title": "Throughput (Transmit)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*',instance_id!=\"__INSTANCE_ID__\"}[1m]))",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Throughput (Receive)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*',instance_id!=\"__INSTANCE_ID__\"}[1m]))",
     "legendFormat": "Receive"
    }
   ]
  },
  { "title": "S3 stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "S3 Throughput (Upload)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "dimensions": { "BucketName": "_S3_BUCKET_" },
     "metricName": "BytesUploaded",
     "namespace": "AWS/S3",
     "region": "__AWS_REGION__",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "S3 Throughput (Download)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "dimensions": { "BucketName": "_S3_BUCKET_" },
     "metricName": "BytesDownloaded",
     "namespace": "AWS/S3",
     "region": "__AWS_REGION__",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}